version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: QA
    working_dir: /home/workspace/frontend
    volumes:
      - ./:/home/workspace
    tty: true
    stdin_open: true
    ports:
      - "30119:80"
      - "30120:5000"
    ipc: host
    networks:
      - qa_network
    restart: unless-stopped
    command: /bin/bash -c "npm run build && /home/workspace/api/start.sh"

  db:
    image: mongo
    container_name: qadb
    ports:
      - "27017:27017"
    networks:
      - qa_network
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=laon
      - MONGO_INITDB_DATABASE=dataset
    restart: unless-stopped

networks:
  qa_network:
    driver: bridge
